# Generated by Django 5.1.2 on 2024-11-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_body_alter_submission_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='body',
            new_name='file',
        ),
    ]
