# Generated by Django 5.1.2 on 2025-02-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_alter_figure_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='model_type',
            field=models.TextField(choices=[('ML', 'Machine Learning'), ('KF', 'Kalman Filter'), ('NA', 'Not Specified')], default='NA', max_length=2),
        ),
    ]
