# Generated by Django 5.1.2 on 2025-03-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='file',
            field=models.FileField(max_length=255, upload_to='matlab_figures/'),
        ),
    ]
