# Generated by Django 5.1.2 on 2025-03-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_submission_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='error_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
