# Generated by Django 5.1.2 on 2025-01-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_testdata_testsuite_testdatafile_testfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdatafile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='testfile',
            name='parent',
        ),
        migrations.AddField(
            model_name='submission',
            name='all_drive_cycles_average_MAE',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='all_drive_cycles_average_MAXE',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='all_drive_cycles_average_RMSE',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='model_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t10_iSOC_error',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t11_current_sensor_error',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t1_all_cells',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t2_blind_cells',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t3_non_blinded_cells',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t4_charging',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t5_1000kg_payload',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t5_6_448kg_payload',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t5_6_448kg_payload_with_HVAC',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t5_80kg_payload',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t7_standard_cycles',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t8_custom_cycles',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t9_0C',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t9_10C',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t9_25C',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t9_40C',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t9_n10C',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='t9_n20C',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='weighted_error',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='TestData',
        ),
        migrations.DeleteModel(
            name='TestDataFile',
        ),
        migrations.DeleteModel(
            name='TestFile',
        ),
        migrations.DeleteModel(
            name='TestSuite',
        ),
    ]
