# Generated by Django 5.1.2 on 2025-02-07 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_figure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='submissions.submission'),
        ),
    ]
