# Generated by Django 5.1.2 on 2025-03-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_submission_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=7),
        ),
    ]
