# Generated by Django 5.1.2 on 2025-03-19 20:34

import submissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_submission_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.TextField(default=submissions.models.generate_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
