# Generated by Django 5.1.2 on 2025-06-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='Social Media Post'),
        ),
    ]
